### ISSUE TITLE
isotovideo frequently crashing in the signal handler stuff (especially on aarch64)

### ISSUE THREAD

**Issue by AdamWill** [os-autoinst/os-autoinst#2549]
Filing a new ticket for this as discussing it in https://github.com/os-autoinst/os-autoinst/pull/1640 was getting confusing.

On the Fedora deployments currently, I'm seeing frequent crashes in isotovideo, in the signal handler stuff that is trying to prevent crashes caused by the perl signal handler trying to handle signals from opencv threads. This is happening especially often on aarch64, but it's also happening on x86_64. It also seems to be causing workers to get into a broken state, as the qemu process from the crashed job hangs around and blocks things. I'm having to kill tons of qemu processes and restart worker processes, or just restart the affected systems periodically, or else I lose all the workers.

The backtraces I get on aarch64 and x86_64 are slightly different. [x86_64 backtrace](https://github.com/user-attachments/files/17136994/x64bt.txt), [aarch64 backtrace](https://github.com/user-attachments/files/17137256/a64bt.txt) . aarch64 shows the signal as 15 and crashes at `(PL_signals & PERL_SIGNALS_UNSAFE_FLAG))`, x86_64 shows the signal as optimized out and crashes at `sig == SIGFPE ||`.

@Vogtinator asked in the earlier discussion if I could "try to get its signal masks", but I honestly have no idea how to do that. I'm a Python coder, damnit. :D If anyone wants to walk me through it, I can try.

**Comment by Martchus** [comment]
> I'm having to kill tons of qemu processes and restart worker processes, or just restart the affected systems periodically, or else I lose all the workers.

Normally the openQA worker is supposed to SIGKILL the whole process group after a timeout. That this is not working is of course yet another issue (which we saw recently as well but so far only on one of our workers).

---

This indeed sounds like the signal mask is not set as it should be on all OpenCV threads. Since OpenCV is spawning the threads on its own and by the help of yet another abstraction library (e.g. TBB) so this isn't straight forward. The current approach is to set the signal mask of the main thread, execute some code that will hopefully fully spawn OpenCV's thread pool and then set back the signal mask of the main process. ~~Maybe our code was not able to fully spawn OpenCV's thread pool so some processes did not inherit the temporarily changed signal mask from the main process.~~ Considering `sig == SIGPE` the problem is more likely that we'll have to take care of this signal as well (which we currently don't do).

**Comment by Vogtinator** [comment]
> @Vogtinator asked in the earlier discussion if I could "try to get its signal masks", but I honestly have no idea how to do that. I'm a Python coder, damnit. :D If anyone wants to walk me through it, I can try.

Unfortunately I don't think it's possible to get them after the fact, as simply catching a signal modifies it.

You can check `grep ^SigBlk /proc/$pid/task/*/status` on running isotovideo processes. The OpenCV threads should have SIGCHLD and SIGTERM blocked in addition.

**Comment by Martchus** [comment]
I also couldn't find a way to read the signal masks of a coredump. The best I can currently think of is to add a few more sanity checks in our code. And you could of course try to monitor the processes with the command @Vogtinator mentioned.

**Comment by Martchus** [comment]
Maybe you can add the check @Vogtinator mentioned somewhere in your production deployments (where you can reproduce the error) like I did it for our tests in https://github.com/os-autoinst/os-autoinst/pull/2551/files#diff-9e94ac1686eef02708b9f17f65398b6799f035b167e417966aca064f40bfa4bd.

**Comment by AdamWill** [comment]
so, looking on the x86_64 worker host, where 2621079 is the pid of a `/usr/bin/isotovideo: backend` process, I get:
```
[adamwill@openqa-x86-worker01 ~][PROD]$ grep ^SigBlk /proc/2621079/task/*/status
/proc/2621079/task/2621079/status:SigBlk:	0000000000000000
/proc/2621079/task/2621142/status:SigBlk:	0000000000014000
/proc/2621079/task/2621143/status:SigBlk:	0000000000014000
/proc/2621079/task/2621144/status:SigBlk:	0000000000014000
/proc/2621079/task/2621145/status:SigBlk:	0000000000014000
/proc/2621079/task/2621146/status:SigBlk:	0000000000014000
/proc/2621079/task/2621147/status:SigBlk:	0000000000014000
/proc/2621079/task/2621148/status:SigBlk:	0000000000014000
/proc/2621079/task/2621149/status:SigBlk:	0000000000014000
/proc/2621079/task/2621150/status:SigBlk:	0000000000014000
/proc/2621079/task/2621151/status:SigBlk:	0000000000014000
/proc/2621079/task/2621152/status:SigBlk:	0000000000014000
/proc/2621079/task/2621153/status:SigBlk:	0000000000014000
/proc/2621079/task/2621154/status:SigBlk:	0000000000014000
/proc/2621079/task/2621155/status:SigBlk:	0000000000014000
/proc/2621079/task/2621156/status:SigBlk:	0000000000014000
/proc/2621079/task/2621157/status:SigBlk:	0000000000014000
/proc/2621079/task/2621158/status:SigBlk:	0000000000014000
/proc/2621079/task/2621159/status:SigBlk:	0000000000014000
/proc/2621079/task/2621160/status:SigBlk:	0000000000014000
/proc/2621079/task/2621161/status:SigBlk:	0000000000014000
/proc/2621079/task/2621162/status:SigBlk:	0000000000014000
/proc/2621079/task/2621163/status:SigBlk:	0000000000014000
/proc/2621079/task/2621164/status:SigBlk:	0000000000014000
/proc/2621079/task/2621165/status:SigBlk:	0000000000014000
/proc/2621079/task/2621166/status:SigBlk:	0000000000014000
/proc/2621079/task/2621167/status:SigBlk:	0000000000014000
/proc/2621079/task/2621168/status:SigBlk:	0000000000014000
/proc/2621079/task/2621169/status:SigBlk:	0000000000014000
/proc/2621079/task/2621170/status:SigBlk:	0000000000014000
/proc/2621079/task/2621171/status:SigBlk:	0000000000014000
/proc/2621079/task/2621172/status:SigBlk:	0000000000014000
/proc/2621079/task/2621173/status:SigBlk:	0000000000014000
/proc/2621079/task/2621174/status:SigBlk:	0000000000014000
/proc/2621079/task/2621175/status:SigBlk:	0000000000014000
/proc/2621079/task/2621176/status:SigBlk:	0000000000014000
/proc/2621079/task/2621177/status:SigBlk:	0000000000014000
/proc/2621079/task/2621178/status:SigBlk:	0000000000014000
/proc/2621079/task/2621179/status:SigBlk:	0000000000014000
/proc/2621079/task/2621180/status:SigBlk:	0000000000014000
/proc/2621079/task/2621181/status:SigBlk:	0000000000014000
/proc/2621079/task/2621182/status:SigBlk:	0000000000014000
/proc/2621079/task/2621183/status:SigBlk:	0000000000014000
/proc/2621079/task/2621184/status:SigBlk:	0000000000014000
/proc/2621079/task/2621185/status:SigBlk:	0000000000014000
/proc/2621079/task/2621186/status:SigBlk:	0000000000014000
/proc/2621079/task/2621187/status:SigBlk:	0000000000014000
/proc/2621079/task/2621188/status:SigBlk:	0000000000014000
/proc/2621079/task/2621189/status:SigBlk:	0000000000014000
/proc/2621079/task/2621190/status:SigBlk:	0000000000014000
/proc/2621079/task/2621191/status:SigBlk:	0000000000014000
/proc/2621079/task/2621192/status:SigBlk:	0000000000014000
/proc/2621079/task/2621193/status:SigBlk:	0000000000014000
/proc/2621079/task/2621194/status:SigBlk:	0000000000014000
/proc/2621079/task/2621195/status:SigBlk:	0000000000014000
/proc/2621079/task/2621196/status:SigBlk:	0000000000014000
/proc/2621079/task/2621197/status:SigBlk:	0000000000014000
/proc/2621079/task/2621198/status:SigBlk:	0000000000014000
/proc/2621079/task/2621199/status:SigBlk:	0000000000014000
/proc/2621079/task/2621200/status:SigBlk:	0000000000014000
/proc/2621079/task/2621201/status:SigBlk:	0000000000014000
/proc/2621079/task/2621202/status:SigBlk:	0000000000014000
/proc/2621079/task/2621203/status:SigBlk:	0000000000014000
```
I get similar output on the a64 worker host (first process is all zeros, others have 14 in the middle). I did see one case where the *last* process in the list was also all zeros, which sounds like maybe it's significant?

**Comment by Vogtinator** [comment]
> I did see one case where the last process in the list was also all zeros, which sounds like maybe it's significant?

Can be, but could also be a perl thread? In such a case you can gdb into it and do `thread apply all bt` to check which threads are perl and which aren't.

**Comment by AdamWill** [comment]
Here's a dumb thing I rigged up:
```
[adamwill@openqa-a64-worker04 ~][PROD-IAD2]$ for i in `ps aux | grep isotovideo | grep backend | cut -d" " -f 2`; do echo "PID $i"; grep ^SigBlk /proc/$i/task/*/status | grep -v 14; done
PID 3886721
/proc/3886721/task/3886721/status:SigBlk:	0000000000000000
PID 3888467
/proc/3888467/task/3888467/status:SigBlk:	0000000000000000
/proc/3888467/task/3899092/status:SigBlk:	0000000000000000
PID 3888866
/proc/3888866/task/3888866/status:SigBlk:	0000000000000000
/proc/3888866/task/3899090/status:SigBlk:	0000000000000000
PID 3888881
/proc/3888881/task/3888881/status:SigBlk:	0000000000000000
/proc/3888881/task/3890061/status:SigBlk:	0000000000000000
PID 3888953
/proc/3888953/task/3888953/status:SigBlk:	0000000000000000
/proc/3888953/task/3899071/status:SigBlk:	0000000000000000
PID 3888981
/proc/3888981/task/3888981/status:SigBlk:	0000000000000000
/proc/3888981/task/3899084/status:SigBlk:	0000000000000000
PID 3902008
/proc/3902008/task/3902008/status:SigBlk:	0000000000000000
/proc/3902008/task/3903786/status:SigBlk:	0000000000000000
PID 3905004
/proc/3905004/task/3905004/status:SigBlk:	0000000000000000
/proc/3905004/task/3907324/status:SigBlk:	0000000000000000
PID 3909654
/proc/3909654/task/3909654/status:SigBlk:	0000000000000000
```
so of the 9 running isotovideo:backend processes on that host ATM, two have one all-zeros threads, seven have two all-zeros threads.

**Comment by AdamWill** [comment]
It doesn't look like 3899092 is a perl thread to me:
```
Thread 2 (Thread 0xfffe9e20f180 (LWP 3899092) "/usr/bin/isotov"):
#0  0x0000ffffb691f7e4 in syscall () from /lib64/libc.so.6
#1  0x0000ffffb2133384 in tbb::detail::r1::binary_semaphore::P() () from /lib64/libtbb.so.12
#2  0x0000ffffb2148728 in tbb::detail::r1::rml::private_worker::thread_routine(void*) () from /lib64/libtbb.so.12
#3  0x0000ffffb68b69d8 in start_thread () from /lib64/libc.so.6
#4  0x0000ffffb6921dcc in thread_start () from /lib64/libc.so.6
```
so...that looks bad, right?

**Comment by Vogtinator** [comment]
Yup, that's broken! Question is why, for which we need to figure out how and when that thread was born.

**Comment by AdamWill** [comment]
Just going by the PIDs it looks "younger" than all the other threads from that process. The parent is 3888467 , its children start at 3888500 and go to 3888578 taking up almost every PID in between (so those obviously spawned as a group), but then jump to 3899092 . So...something is causing one extra thread to show up late?

Fiddling around with ps a bit, it looks like it started about 30 seconds after all the others:
```
ps -o spid,lstart,cmd -T -p 3888467
   SPID                  STARTED CMD
...
3888578 Mon Sep 30 15:09:54 2024 /usr/bin/isotovideo: backend
3899092 Mon Sep 30 15:10:23 2024 /usr/bin/isotovideo: backend
```

**Comment by AdamWill** [comment]
Here's the full backtrace of that thread:
```
Thread 2 (Thread 0xfffe9e20f180 (LWP 3899092) "/usr/bin/isotov"):
#0  syscall () at ../sysdeps/unix/sysv/linux/aarch64/syscall.S:38
No locals.
#1  0x0000ffffb2133384 in tbb::detail::r1::futex_wait (comparand=2, futex=0xffff07706a24) at /usr/src/debug/tbb-2021.11.0-5.fc40.aarch64/src/tbb/semaphore.h:100
        r = <optimized out>
#2  tbb::detail::r1::binary_semaphore::P (this=0xffff07706a24) at /usr/src/debug/tbb-2021.11.0-5.fc40.aarch64/src/tbb/semaphore.h:253
        s = <optimized out>
#3  0x0000ffffb2148728 in tbb::detail::r1::rml::internal::thread_monitor::wait (this=0xffff07706a20) at /usr/src/debug/tbb-2021.11.0-5.fc40.aarch64/src/tbb/rml_thread_monitor.h:235
No locals.
#4  tbb::detail::r1::rml::private_worker::run (this=0xffff07706a00) at /usr/src/debug/tbb-2021.11.0-5.fc40.aarch64/src/tbb/private_server.cpp:273
        j = @0xffff05d8ff00: {<No data fields>}
        j = <optimized out>
#5  tbb::detail::r1::rml::private_worker::thread_routine (arg=0xffff07706a00) at /usr/src/debug/tbb-2021.11.0-5.fc40.aarch64/src/tbb/private_server.cpp:221
        self = 0xffff07706a00
#6  0x0000ffffb68b69d8 in start_thread (arg=0xfffe9e20f180) at pthread_create.c:447
        ret = <optimized out>
        pd = 0xfffe9e20f180
        out = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {281469035544576, 4194304, 281469039733176, 281473751096192, 281473744332384, 0, 281474089107415, 4254272, 281473751094336, 281469035479040, 281469039733264, 7036161307687183712, 0, 7036161312394668596, 0, 0, 0, 0, 0, 0, 0, 0}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = 0
#7  0x0000ffffb6921dcc in thread_start () at ../sysdeps/unix/sysv/linux/aarch64/clone3.S:76
No locals.
```
is there anything else I can get from gdb to help figure out how it got born?

**Comment by AdamWill** [comment]
sorry, I got pulled away onto other stuff, but trying to get back to this. we'd have to patch os-autoinst to launch isotovideo that way and dump the output somewhere, right? i'll see if I can fiddle with that next.

**Comment by AdamWill** [comment]
poking about at this...on a host with 64 CPUs (according to `/proc/cpuinfo` anyhow), counting threads with the `grep ^SigBlk /proc/(PID)/task/*/status` trick, the count seems kinda interesting. In a process where the last thread has 14 in the mask, there are 63 total threads - one 00 thread, then 62 14 threads. In a process where the last thread has 00 in the mask, there are 64 total threads - one 00 thread, 62 14 threads, another 00 thread.

I'm wondering: do we have an off-by-one here? Are we pre-creating one thread fewer than we ought to somehow?

Looking at the logic in `tinycv_impl.cc`, I'd kind *expect* us to get a thread count of 63 on this system. So we should pre-create 63 signal-blocked threads, right? But we only seem to create 62. I don't know why, though. Is the last iteration of the `parallel_for_` loop suspect in any way?

**Comment by AdamWill** [comment]
So I hacked up os-autoinst to dump out the relevant numbers, and that confirms my expectation:
```
XXX cv::getNumThreads: 64
XXX cv::getNumberofCPUs: 64
XXX thread count: 63
```
That "thread count" is the value of `thread_count` in `create_opencv_threads` right before it does `cv::setNumThreads(thread_count);`. So if it's 63, why does it look like we create only *62* blocked threads?

**Comment by AdamWill** [comment]
Hah! So...I think a silly guess I had about this was right.

I think the first iteration of the `parallel_for_` loop runs on *the parent thread*. It doesn't create a new thread. So we actually wind up creating *one fewer thread* than we intend to.

I hacked up the loop to print its tid, how many threads have been spawned so far, and whether it's the final iteration:

        FILE *f = fopen(fn, "a");
        fprintf(f, "locking TID: %d\n", tid);
        if (++threads_spawned >= thread_count) {
            fprintf(f, "threads spawned: %d\n", threads_spawned);
            fprintf(f, "LAST ITERATION!\n");
            cv.notify_all(); // note: The last thread releases all previously spawned threads.
        } else {
            fprintf(f, "threads spawned: %d\n", threads_spawned);
            cv.wait(lock);
        }
        fclose(f);

(that was covering a few possibilities), and let's take a look at the output for one case:

locking TID: 1247877
threads spawned: 1

what's interesting about that? well, 1247877 is the pid of the backend process in question:

[root@openqa-x86-worker05 adamwill][PROD-IAD2]# ps aux | grep backend
_openqa+ 1247877  9.2  0.1 13256444 305668 ?     Sl   17:18   0:38 /usr/bin/isotovideo: backend

all the other TIDs we log as being locked are new threads that show up under `/proc/1247877/task`. So, I think this loop that tries to create 63 threads actually just locks the parent thread on the first iteration, then creates *62* threads on the subsequent iterations.

**Comment by AdamWill** [comment]
uff, maybe not. if I change that code to try and spawn one more thread, the tests fail because isotovideo doesn't start up (presumably it's deadlocked trying to start the last thread). but then how can we get one extra thread when the bug happens? ehh. now I'm more confused than before. :D

**Comment by AdamWill** [comment]
oh, I forgot to mention, I have been trying the strace thing too but haven't yet seemingly managed to hit the bug that way. I edited `openqa-worker-plain@.service` to run through strace:
`ExecStart=strace -o /var/tmp/oqastrace-%i.txt -fketrace=clone,clone3 /usr/share/openqa/script/worker --instance %i`
and restarted a worker several times and let it pick up a job then waited a few minutes, but never managed to catch the relevant worker's backend process with an extra thread :/ I'll try it a few more times, maybe I'll get lucky.

**Comment by AdamWill** [comment]
sigh, I tried another crazy guess but it didn't work. there definitely seems to be a shy bug element to this: I really just *cannot* get it to trigger when running under strace. But I don't see how running under strace would prevent it from happening :/ annoying.

**Comment by Martchus** [comment]
I'll have a look into your suspicion that this spawns one thread too less and maybe adjust my pending PR to extend tests and change the implementation if necessary. If it is really just that it would be great - otherwise this problem would likely be very hard to fix (because even if you can pinpoint the thread creation it will most likely be within tbb and we can't just intercept that).

**Comment by AdamWill** [comment]
I'm not confident about that because I tried making it create one more thread and that caused the tests to time out, presumably because isotovideo never fully started up :(

The other thing I tried was having opencv's setNumThreads set the *tbb* limit one lower than the limit we gave opencv (in case tbb interprets the cap differently from opencv and will create one extra thread in some situation), but that didn't seem to help either, rogue unmasked threads still showed up :/

My other crazy idea is that maybe the limit at opencv and/or tbb level is getting reset to the default at some point somehow, and the default is one higher than the one we calculate and set with setNumThreads. But I can't really think of a way to even check that, let alone fix it. And that might not be it at all. :|

**Comment by AdamWill** [comment]
I figured it can't hurt to call in some more brains, so I posted this [to the OpenCV forums](https://forum.opencv.org/t/opencv-on-tbb-creating-one-more-thread-than-expected/18953).

**Comment by Martchus** [comment]
I had a quick look at the code. It uses the following formula to determine the number of threads to spawn: `std::max(1, std::min(cv::getNumThreads(), cv::getNumberOfCPUs() - 1));`.

So we always spawn at least one thread. We try to use `cv::getNumThreads()` which makes sense. However, we spawn less threads if the number of actual CPUs is lower. I vaguely remember we put that additional limit in because otherwise it would deadlock on some systems (indicating that TBB itself applies a similar limit). The commit message 8363ce364ec381e3e45a72d2028c8caf609a6811 confirms this.

The commit message doesn't states why I put the ` -1` into the formula and that `-1` could actually be the reason why sometimes too few threads are created. I left it out and without it the test still did not deadlock - even if I set `cv::setNumThreads(1000);` as first step in `opencv_default_thread_count()` so the minimum of `cv::getNumberOfCPUs()` is effective. And if I use `cv::getNumberOfCPUs() + 1` with that modifications the test really deadlocks. So supposedly `cv::getNumberOfCPUs()` should be the limit (and not `-1` or `+1`).

**Comment by Martchus** [comment]
I pushed another change to https://github.com/os-autoinst/os-autoinst/pull/2551 which should fix the `-1` problem.

**Comment by Martchus** [comment]
By the way, we actually have also a [ticket about that](https://progress.opensuse.org/issues/53999) and the problem is probably still reproducible (as we have loots of crashes according to coredumpctl on production workers; I haven't looked into any of them recently, though).

**Comment by AdamWill** [comment]
yeah, I saw that, but the thing is, we also run `cv::setNumThreads(thread_count);` - that is, whatever we decide the limit should be, we tell opencv to make that the limit. So in theory it *shouldn't* matter too much what the result of that calculation is. If removing the `cv::getNumberOfCPUs() - 1)` 'fixes' it, that to me would imply support for my "the limits somehow gets reset to default later" theory, and now we're avoiding that by just using the same value as the defaults. (This gets pretty fuzzy when you try to account for limits existing at both opencv and tbb levels, plus the notion of 'soft' and 'hard' limits).

I was going to come at the same thing from a slightly different angle today: I was going to set `thread_count` to an arbitrarily low value, like say 4, and then see if we wound up with 4 subthreads, 5 subthreads, or 63 subthreads. I'll try and get to that later.

**Comment by AdamWill** [comment]
BTW, the commit message might not explain the -1, but the comment above it does:

"To avoid running into TBB's soft limit which seems to be one thread less than the number of physical CPU threads (see TBB function `calc_workers_soft_limit`) we also limit ourselves to that. Otherwise we might run into a deadlock with "The number of workers is currently limited to 7. The request for 8 workers is ignored.""

the quoted error message reads a lot like this is a real thing that somebody ran into, so changing it does worry me a bit.

**Comment by Martchus** [comment]
Right, there's actually an explaining comment. Maybe the mentioned TBB function has changed. I'll look into it.

And yes, I've also noticed that we actually set the thread count explicitly. So I'm theory we would only lose the ability to make use of one of the CPU cores. However, in practice the call might be overridden like you've already stated so my change might still help.

**Comment by AdamWill** [comment]
My guess is there's maybe some subtlety to how the various limits get calculated on different hardware and dropping the `-1` might be fine in some cases but break in others, but I got lost trying to dig into it all :/

**Comment by AdamWill** [comment]
oh, hum, just noticed something about the strace attempts - running 10 workers on the host with the strace setup at once was apparently too heavy, a lot of the tests were basically getting stuck right at the start and failing, which might explain why they never got as far as spawning an extra thread. i'll go back to testing with just one worker rigged through strace (though I already did that enough times that I *should* have hit the big at least once, but maybe I was just unlucky...)

**Comment by Martchus** [comment]
It doesn't look like `calc_workers_soft_limit` has changed as it still uses ` -1` in the computation: https://github.com/oneapi-src/oneTBB/blob/94bee9c86b4b342cd2eb46270f0c62b8edd4c76d/src/tbb/threading_control.cpp#L55

And `governor::default_num_threads()` is probably really just returning the numbers of CPU cores in-line with what we're using (although the code in https://github.com/oneapi-src/oneTBB/blob/master/src/tbb/misc_ex.cpp is a bit too much to make sense of in just a brief read).

After having a look at the code I'm wondering whether it makes sense for us to [set the global parameter `max_allowed_parallelism`](https://oneapi-spec.uxlfoundation.org/specifications/oneapi/v1.2-provisional-rev-1/elements/onetbb/source/task_scheduler/scheduling_controls/global_control_cls) explicitly so the behavior of TBB is more predictive.

**Comment by AdamWill** [comment]
interesting idea. the obvious drawback of that is it effectively mandates that the opencv in our deployment be built against tbb :/ unless we hedge it around with checks that the opencv deployment *is* built against tbb, of course.

I might actually try doing that in opencv `setNumThreads`'s specific-to-tbb branch, though if that fixes it, who knows whether upstream would take that patch :/

**Comment by AdamWill** [comment]
OK, so I tried the 'arbitrarily cap the thread count we use to a really low number' thing:
```
diff --git a/ppmclibs/tinycv_impl.cc b/ppmclibs/tinycv_impl.cc
index cb6c2586..5b382286 100644
--- a/ppmclibs/tinycv_impl.cc
+++ b/ppmclibs/tinycv_impl.cc
@@ -355,6 +355,7 @@ void create_opencv_threads(int thread_count)
     if (thread_count < 0) {
         thread_count = opencv_default_thread_count();
     }
+    thread_count = std::min(4, thread_count);
     cv::setNumThreads(thread_count);
 
     // execute a parallel algorithm which ensures that \a thread_count are busy at the same time
```
and the results are interesting! Soon after they start, worker backends running that build have four threads:
```
[root@openqa-x86-worker05 adamwill][PROD-IAD2]# for i in `ps aux | grep isotovideo | grep backend | cut -d" " -f 2`; do echo "PID $i"; grep ^SigBlk /proc/$i/task/*/status | wc -l; done
...
PID 2472874
4
PID 2475517
4
```
but in the time it took me to make a coffee, they're growing more:
```
[root@openqa-x86-worker05 adamwill][PROD-IAD2]# for i in `ps aux | grep isotovideo | grep backend | cut -d" " -f 2`; do echo "PID $i"; grep ^SigBlk /proc/$i/task/*/status | wc -l; done
...
PID 2472874
7
PID 2481995
7
PID 2484243
10
```
so, that kinda supports the 'cap isn't hard enough or is getting reset later' theory. Unsurprisingly, all the threads after the fourth have an all-zero sigmask:
```
[root@openqa-x86-worker05 adamwill][PROD-IAD2]# grep ^SigBlk /proc/2484243/task/*/status
/proc/2484243/task/2484243/status:SigBlk:	0000000000000000
/proc/2484243/task/2484244/status:SigBlk:	0000000000014000
/proc/2484243/task/2484245/status:SigBlk:	0000000000014000
/proc/2484243/task/2484246/status:SigBlk:	0000000000014000
/proc/2484243/task/2486170/status:SigBlk:	0000000000000000
/proc/2484243/task/2486171/status:SigBlk:	0000000000000000
/proc/2484243/task/2486172/status:SigBlk:	0000000000000000
/proc/2484243/task/2486173/status:SigBlk:	0000000000000000
/proc/2484243/task/2486174/status:SigBlk:	0000000000000000
/proc/2484243/task/2486175/status:SigBlk:	0000000000000000
```

I've also got an opencv build running with this change:
```
diff --git a/modules/core/src/parallel.cpp b/modules/core/src/parallel.cpp
index 5799d73599..841be3b3ac 100644
--- a/modules/core/src/parallel.cpp
+++ b/modules/core/src/parallel.cpp
@@ -108,6 +108,9 @@
     #endif
     #include "tbb/tbb.h"
     #include "tbb/task.h"
+    #if TBB_INTERFACE_VERSION >= 8005
+        #include "tbb/global_control.h"
+    #endif
     #if TBB_INTERFACE_VERSION >= 8000
         #include "tbb/task_arena.h"
     #endif
@@ -727,7 +730,9 @@ void setNumThreads( int threads_ )
     }
 
 #ifdef HAVE_TBB
-
+#if TBB_INTERFACE_VERSION >= 8005
+    tbb::global_control tbb_cont(tbb::global_control::max_allowed_parallelism, threads);
+#endif
 #if TBB_INTERFACE_VERSION >= 8000
     if(tbbArena.is_active()) tbbArena.terminate();
     if(threads > 0) tbbArena.initialize(threads);
```
I'll try deploying that onto my test worker host and see what happens.

**Comment by AdamWill** [comment]
sigh. nope. with both patches applied, we're getting processes with up to 10 threads. somehow, opencv/tbb are definitely creating more threads than we are telling them to.

**Comment by AdamWill** [comment]
I've not been focusing on this lately for a couple of reasons:

1. It's F41 release crunch
2. I implemented a stupid workaround for it which seems to be working okay (a cron job which parses systemctl output to find stuck qemu processes and kill them once a day, that causes the worker to recover on its next checkin)

it's still a problem, though, and I wouldn't want to rely on the dumb workaround for too long.

**Comment by AdamWill** [comment]
yeah, I feel like something there changed relatively recently, though I'm not sure *precisely* when. Because I'm pretty sure the crashes have been happening all along but we weren't really getting stuck workers till more recently. Might be when I upgraded the workers to Fedora 40, or something. They have perl-Mojo-IOLoop-ReadWriteProcess-0.34-3 .

I don't think it's any specific worker host because this is affecting several of them, would be odd for them all to go wrong at once...

**Comment by AdamWill** [comment]
So I figured out one interesting thing here at least. It seems one of the most common cases where we hit this bug on Fedora openQA is in the one case where we have an OCR needle: https://pagure.io/fedora-qa/os-autoinst-distri-fedora/blob/335981088776797eb7d2b417d34d4442ede72e62/f/needles/gnome/apps/tour/tour_start.json

The one test that actually uses that needle seems to hit this crash about 30% of the time, right after encountering that needle.

I do see that we run tesseract via `system()` for ocr needles, which felt like it might be significant...but I tried this:
```
diff --git a/ocr.pm b/ocr.pm
index e12bf66b..4e3ca4e4 100644
--- a/ocr.pm
+++ b/ocr.pm
@@ -4,6 +4,7 @@
 
 package ocr;
 use Mojo::Base -strict, -signatures;
+use signalblocker;
 require IPC::System::Simple;
 
 sub tesseract ($img, $area) {
@@ -16,8 +17,10 @@ sub tesseract ($img, $area) {
     }
 
     $img->write($imgfn);
+    my $signal_blocker = signalblocker->new;
     # disable debug output, because new versions by default only reports errors and warnings
     system("tesseract $imgfn $txtfn quiet");
+    undef $signal_blocker;
     $txtfn .= '.txt';
     open(my $fh, '<:encoding(UTF-8)', $txtfn);
     local $/;
```
and it doesn't seem to help, unfortunately. However, completely removing the OCR area from the needle does help, I did 20 runs of the test after that with a 100% success rate.

It doesn't look like this is the *only* case where we hit this crash, but it seems to be a pretty significant source of them. I'm going to push out the needle change and see how often the crash happens after that.

(Note OCR seems to be broken anyway - the OCR area of the needle is trying to match the text "Start the Tour", but when it doesn't crash, we pass the needle match even though the current screen does not have "Start the Tour" on it anywhere...)

**Comment by Vogtinator** [comment]
The use of `system` shouldn't need signalblocker: it does not create a thread AFAIK but only a fork instead which gets replaced with the tesseract process. The reason it's still relevant here is the other way around: When the tesseract process dies, the SIGCHLD signal gets delivered to a random thread of the parent process which doesn't have the signal masked. If that happens to be a thread not created by perl, it crashes.

Without OCR needles, do you still the the additional thread with a signal mask of all zeros?

**Comment by AdamWill** [comment]
ah, I see. I didn't check that part, I'll maybe check when I get back from the holidays.

**Comment by AdamWill** [comment]
yeah, it looks like we are still getting that:
```
[adamwill@openqa-x86-worker02 ~][PROD-IAD2]$ for i in `ps aux | grep isotovideo | grep backend | cut -d" " -f 2`; do echo "PID $i"; grep ^SigBlk /proc/$i/task/*/status | grep -v 14; done
PID 3886721
PID 1552039
/proc/1552039/task/1552039/status:SigBlk:	0000000000000000
/proc/1552039/task/1552256/status:SigBlk:	0000000000000000
PID 1604378
/proc/1604378/task/1604378/status:SigBlk:	0000000000000000
PID 1606652
/proc/1606652/task/1606652/status:SigBlk:	0000000000000000
/proc/1606652/task/1608269/status:SigBlk:	0000000000000000
PID 1608588
/proc/1608588/task/1608588/status:SigBlk:	0000000000000000
PID 1608589
/proc/1608589/task/1608589/status:SigBlk:	0000000000000000
PID 1612003
/proc/1612003/task/1612003/status:SigBlk:	0000000000000000
PID 1614219
```
so that host has six without and two with ATM. The crashes are also still happening, maybe at a slightly reduced rate but it's hard to be sure :/
